### ISSUE TITLE
Weingartner.Json.Migration.Roslyn.MigrationHashAnalyzer cannot be created

### ISSUE THREAD

**Issue by michalciolek** [Weingartner/Migrations.Json.Net#11]
Hello, I use `Weingartner.Json.Migration.Analyzer 2.1.2` nuget and analyzers do not works. They do not show error when I change code in `Migratable` class.
Compiler output:
```
1>CSC : warning CS8032: An instance of analyzer Weingartner.Json.Migration.Roslyn.MigrationHashAnalyzer cannot be created from C:\Users\xx\.nuget\packages\weingartner.json.migration.analyzer\2.1.2\analyzers\dotnet\cs\Weingartner.Json.Migration.Roslyn.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. File not found..
1>CSC : warning CS8032: An instance of analyzer Weingartner.Json.Migration.Roslyn.DataContractAnalyzer cannot be created from C:\Users\xx\.nuget\packages\weingartner.json.migration.analyzer\2.1.2\analyzers\dotnet\cs\Weingartner.Json.Migration.Roslyn.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. File not found..
1>CSC : warning CS8032: An instance of analyzer Weingartner.Json.Migration.Roslyn.MigrationMethodAnalyzer cannot be created from C:\Users\xx\.nuget\packages\weingartner.json.migration.analyzer\2.1.2\analyzers\dotnet\cs\Weingartner.Json.Migration.Roslyn.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. File not found..
```

Manualy adding `Microsoft.CodeAnalysis` nuget to project do not solve problem.

**Comment by JKronberger** [comment]
Using Weingartner.Json.Migration (v2.1.2) together with Weingartner.Json.Migration.Analyzers (v2.1.2) in a .net framework 4.8 project in VS2019 works fine. Please share some more information (project framework), to nail this issue down...

**Comment by ErwinFuchs** [comment]
Johannes können wir eine Lösung finden, bei der ich aus dem Github verschwinde ?

Erwin

Von: JKronberger <notifications@github.com>
Gesendet: Mittwoch, 27. Mai 2020 12:10
An: Weingartner/Migrations.Json.Net <Migrations.Json.Net@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Weingartner/Migrations.Json.Net] Weingartner.Json.Migration.Roslyn.MigrationHashAnalyzer cannot be created (#11)


Using Weingartner.Json.Migration (v2.1.2) together with Weingartner.Json.Migration.Analyzers (v2.1.2) in a .net framework 4.8 project in VS2019 works fine. Please share some more information (project framework), to nail this issue down...

**Comment by michalciolek** [comment]
I solve problem using this solutions https://stackoverflow.com/a/44152052
